Work №3
NovikVeronika/itirod pull request #2
Opened 2022-04-04 16:29 UTC by NovikVeronika

https://novikveronika.github.io/itirod/

I tried to do it nice, but i hope you like it. I also have a GiveUpPage, but you cannot access it due to absence of any elements with according actions. 

Warning: not suitable for mobile version (you can try it yourself but don't be angry with me after it.....))))
Can you tell me which functions i should implement for the 4th work :)
Thanks for your patience! :)

2022-04-05 13:01 UTC, katetushkan requested changes
U need to fix problem I mentioned in comments. It doesn't have a mobile version, though. If u wanna more than `8` u need to add it, as well as focus/hover styles to ur buttons.

2022-04-05 13:01 UTC, katetushkan commented on html/StartPlantingPage.html
> +        <button class="rbutton" onclick="window.location.href='StartPage.html'">Start</button>
I think u don't need href here) Should it start the timer?

2022-04-05 13:01 UTC, katetushkan commented on html/StartPlantingPage.html
> +        <label class="for-label">FOR</label>
Should be '<p>' or `<small>`. `<label>` could be only used with the `<input>`

2022-04-05 13:01 UTC, katetushkan commented on html/SignUpPage.html
> +    <p>USER NAME</p>
Only `<label>` could be used with the `<input>`

2022-04-05 13:01 UTC, katetushkan commented on index.html
> +    <p>USER NAME</p>
Same for `<label>` here

2022-04-05 13:01 UTC, katetushkan commented on css/siteStyle.css
> +    height: 18vh;
don't use vh, it could be tricky on moblie devices.

2022-04-05 13:01 UTC, katetushkan commented on css/siteStyle.css
> +    padding-top: 18vh;
same here. use rem

2022-04-05 13:01 UTC, katetushkan commented on css/siteStyle.css
> +    padding-top: 18vh;
also it's better to have body with margins and padding 0. Use margins for ur inner components

2022-04-05 13:01 UTC, katetushkan commented on css/StartPlantingPage.css
> +aside{
use class

2022-04-05 13:01 UTC, katetushkan commented on css/LoggedPage.css
> +    /*display: flex;*/
should be flex if u wanna full screen it

2022-04-05 13:01 UTC, katetushkan commented on css/siteStyle.css
> +    height: 100vh;
no. 100%

2022-04-05 13:01 UTC, katetushkan commented on css/SignUpPage.css
> +    position: fixed;
position fix delete elements from the elements flow. if u wanna place it center so this :
1) make container for form flex;
2) set flex-shrink for kids.

2022-04-05 13:01 UTC, katetushkan commented on css/LoggedPage.css
> +    position: fixed;
no fixed.

2022-04-05 18:46 UTC, NovikVeronika commented on html/StartPlantingPage.html
> +        <button class="rbutton" onclick="window.location.href='StartPage.html'">Start</button>
Yes, it should. At first i thought that the start would be a jump to a new page, but now i understand that this is unnecessary. I added all the changes. Now it works correctly in mobile version too. :)

2022-04-11 13:03 UTC, katetushkan approved these changes
`9` is urs.

2022-04-16 12:20 UTC, merged